// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class Document {
    /**
     * Creates a new Document instance.
     * @param {Partial<Document>} [$$source = {}] - The source object to create the Document.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * 主键id
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("tag" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tag"] = "";
        }
        if (!("cover" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cover"] = "";
        }
        if (!("create_time" in $$source)) {
            /**
             * 注册时间
             * @member
             * @type {number}
             */
            this["create_time"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Document instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Document}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Document(/** @type {Partial<Document>} */($$parsedSource));
    }
}
