// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sqlite3$0 from "../sqlite3/models.js";

/**
 * @returns {Promise<string> & { cancel(): void }}
 */
export function HelloWorld() {
    let $resultPromise = /** @type {any} */($Call.ByID(2747849137));
    return $resultPromise;
}

/**
 * @returns {Promise<(sqlite3$0.Document | null)[]> & { cancel(): void }}
 */
export function ListDocument() {
    let $resultPromise = /** @type {any} */($Call.ByID(370955048));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType2($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

// Private type creation functions
const $$createType0 = sqlite3$0.Document.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
